change ipa-publish

diff --git a/ipa-publish b/ipa-publish
--- a/ipa-publish
+++ b/ipa-publish
@@ -1,12 +1,15 @@
 #!/bin/bash
 
 #--------------------------------------------
-# 功能：为xcode工程打ipa包，并创建发布文件
+# 功能：创建符合itms-services协议的发布文件
 # 作者：ccf
 # E-mail:ccf.developer@gmail.com
 # 创建日期：2012/09/24
 #--------------------------------------------
-
+# 修改日期：2012/09/27
+# 修改人：ccf
+# 修改内容：去掉打包的部分脚本，只保留生成协议文件部分，以后此脚本依赖ipa-build脚本
+#--------------------------------------------
 
 
 #须配置内容  start
@@ -17,12 +20,12 @@ pulish_url="http://webfrogs.github.com/urls/"
 #可配置内容  end
 
 #参数判断
-if [ $# != 2 ];then
-	echo "Params error!"
-	echo "Need two params: 1.path of project 2.name of ipa file"
+if [ $# != 2 ] && [ $# != 1 ];then
+	echo "Number of params error! Need one or two params!"
+	echo "1.root path of project(necessary) 2.name used to display when installing"
 	exit
 elif [ ! -d $1 ];then
-	echo "The first param is not a dictionary."
+	echo "The param must be a dictionary."
 	exit	
 	
 fi
@@ -32,39 +35,48 @@ fi
 cd $1
 project_path=$(pwd)
 
+#判断所输入路径是否是xcode工程的根路径
+ls | grep .xcodeproj > /dev/null
+rtnValue=$?
+if [ $rtnValue != 0 ];then
+	echo "Error!! The param must be the root path of a xcode project."
+	exit
+fi
+
+#判断是否执行过ipa-build脚本
+ls ./build/ipa-build/*.ipa &>/dev/null
+rtnValue=$?
+if [ $rtnValue != 0 ];then
+	echo "Error!! No ipa files exists.Please run the \"ipa-build\" shell script first"
+	exit
+fi
+
+
 #IPA名称
+if [ $# = 2 ];then
 ipa_name=$2
+fi
 
 #build文件夹路径
 build_path=${project_path}/build
 
-#编译工程
-cd $project_path
-xcodebuild || exit
-
-#打包
-cd $build_path
-if [ -d ./ipa-build ];then
-	rm -rf ipa-build
-fi
-mkdir -p ipa-build/Payload
-cp -r ./Release-iphoneos/*.app ./ipa-build/Payload/
-cd ipa-build
-zip -r ${ipa_name}.ipa *
-rm -rf Payload
-
-
-#生成发布文件
-
-cd $project_path
-#取版本号
-bundleVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleShortVersionString" `find . -name "*-Info.plist"`)
+#工程配置文件路径
+project_name=$(ls | grep xcodeproj | awk -F.xcodeproj '{print $1}')
+project_infoplist_path=${project_path}/${project_name}/${project_name}-Info.plist
+#取build值
+bundleVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleVersion" ${project_infoplist_path})
 #取bundle Identifier前缀
 bundlePrefix=$(/usr/libexec/PlistBuddy -c "print CFBundleIdentifier" `find . -name "*-Info.plist"` | awk -F$ '{print $1}')
+
+#生成发布文件
 
 #拷贝ipa
 cd $build_path
 target_name=$(basename ./Release-iphoneos/*.app | awk -F. '{print $1}')
+if [ $# = 1 ];then
+ipa_name="${target_name}"
+fi
+
 if [ -d ./$target_name ];then
 	rm -rf $target_name
 fi
